spring:
  profiles:
    active: dev


---
# Coloque aqui suas configurações de Homologação
spring:
  profiles: homo

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/estoque?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
